
#ifndef SOURCE_DIRECTORY__SRC_DOCTESTDEFINE_H_
#define SOURCE_DIRECTORY__SRC_DOCTESTDEFINE_H_

#ifndef DOCTEST_CONFIG_DISABLE
#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#endif

#endif /* SOURCE_DIRECTORY__SRC_DOCTESTDEFINE_H_ */
